name: WebApp Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ttchatbaard1.azurecr.io
        username: ttchatbaard1
        password: DBd3B4LZoDC6B0tDy5Z5eASHmtObNnmodrXicPSIkK+ACRA6rEPG
    
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:
        docker pull ttchatbaard1.azurecr.io/rag-webapp:latest || true;
        docker build . --file docker/WebApp.Dockerfile --cache-from ttchatbaard1.azurecr.io/rag-webapp:latest --tag ttchatbaard1.azurecr.io/rag-webapp:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag ttchatbaard1.azurecr.io/rag-webapp:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER ttchatbaard1.azurecr.io/rag-webapp:latest;
        docker push ttchatbaard1.azurecr.io/rag-webapp:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push ttchatbaard1.azurecr.io/rag-webapp:latest;